name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          choco install swig
          python -m pip install --upgrade pip
          pip install tox
          pip install --no-cache-dir -e .
        shell: powershell

      - name: Run unit tests
        run: tox -- -v

      - name: Run CLI
        shell: bash
        run: |
          ykman --version
          [[ -z "$(ykman --version | grep -E "not found|missing")" ]]
